#!/usr/bin/env node

const cp = require("child_process");

const tasks = {
  client: {
    cmd: "npx",
    args: ["vite", "--host"],
    cwd: "app/gui",
  },
  server: {
    cmd: "npx",
    args: ["nodemon", "server.ts"],
    cwd: "app/server",
  },
};

function run() {
  for (var task in tasks) {
    const { cmd, args, cwd } = tasks[task];
    cp.spawn(
      cmd,
      args,
      { cwd },
      {
        stdio: "inherit",
        shell: true,
      }
    );
    console.log("Spawned", task);
  }
}

run();
